export const mockFeed = [
	{
		profilePic: "https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-placeholder-png-image_3918418.jpg",
		name: "John Doe",
		username: "johndoe",
		time: "1h",
		content: "This is a post!",
		likes: 10,
		comments: 5,
		shares: 2,
	},
	{
		profilePic: "https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-placeholder-png-image_3918418.jpg",
		name: "Jane Doe",
		username: "janedoe",
		time: "2h",
		content: "This is another post!",
		likes: 20,
		comments: 10,
		shares: 5,
	},
	{
		profilePic: "https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-placeholder-png-image_3918418.jpg",
		name: "John Smith",
		username: "johnsmith",
		time: "3h",
		content: "This is yet another post!",
		likes: 30,
		comments: 15,
		shares: 7,
	},
	{
		profilePic: "https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-placeholder-png-image_3918418.jpg",
		name: "Jane Smith",
		username: "janesmith",
		time: "4h",
		content: "This is the last post!",
		likes: 40,
		comments: 20,
		shares: 10,
	},
	{
		profilePic: "https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-placeholder-png-image_3918418.jpg",
		name: "John Doe",
		username: "johndoe",
		time: "1h",
		content: "This is a post!",
		likes: 10,
		comments: 5,
		shares: 2,
	},
	{
		profilePic: "https://png.pngtree.com/png-clipart/20210915/ourmid/pngtree-user-avatar-placeholder-png-image_3918418.jpg",
		name: "Jane Doe",
		username: "janedoe",
		time: "2h",
		content: "This is another post!",
		likes: 20,
		comments: 10,
		shares: 5,
	},
];
